version: '3.7'
services:
  api:
    image: "leokraken/py-reports:latest"
    container_name: py-reports
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pyreports.rule=Host(`pyreports.api.granbestiapop.com`)"
      - "traefik.http.routers.pyreports.entrypoints=websecure"
      - "traefik.http.routers.pyreports.tls.certresolver=myresolver"
      - "traefik.http.middlewares.pyreports.redirectscheme.scheme=https"
      - "traefik.docker.network=traefik-template_traefik-net"
    ports:
      - "5000:5000"
    network_mode: bridge
    secrets:
      - github_client
      - github_client_secret
    networks:
      - traefik-template_traefik-net

secrets:
   github_client:
     file: github_client.txt
   github_client_secret:
     file: github_client_secret.txt
networks:
   traefik-template_traefik-net:
     external:
       name: traefik-template_traefik-net
